"""
Google Sheets integration helper.

Requires:
  - GOOGLE_SHEETS_SA_JSON env var: base64-encoded service account JSON key
    (Sheets API + Drive API must both be enabled on the Cloud project)

Optional:
  - GOOGLE_DRIVE_FOLDER_ID env var: ID of a Drive folder shared with the
    service account (Editor). Sheets are moved there after creation so they
    count against the folder owner's quota, not the service account's.

One-time setup:
  1. Google Cloud Console → enable Sheets API + Drive API
  2. IAM & Admin → Service Accounts → Create → download JSON key
  3. Base64-encode: base64 -w0 service-account.json
  4. Add as GOOGLE_SHEETS_SA_JSON env var in Render
"""
from __future__ import annotations

import base64
import json
import os
import re

import gspread
import openpyxl
from google.oauth2.service_account import Credentials
from google.auth.transport.requests import AuthorizedSession

SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
]

_DRIVE_FILES_URL = "https://www.googleapis.com/drive/v3/files"


def is_configured() -> bool:
    """Return True if the Google Sheets env var is present."""
    return bool(os.environ.get("GOOGLE_SHEETS_SA_JSON", "").strip())


def _decode_sa_json() -> dict:
    """Decode the base64 service account JSON from the env var."""
    raw = os.environ.get("GOOGLE_SHEETS_SA_JSON", "").strip()
    if not raw:
        raise RuntimeError(
            "GOOGLE_SHEETS_SA_JSON env var is not set. "
            "Follow the setup instructions to configure Google Sheets integration."
        )
    try:
        return json.loads(base64.b64decode(raw + "=="))
    except Exception as exc:
        raise RuntimeError(f"Could not decode GOOGLE_SHEETS_SA_JSON: {exc}") from exc


def _client() -> gspread.Client:
    """Return an authenticated gspread Client (gspread v6 native method)."""
    info = _decode_sa_json()
    return gspread.service_account_from_dict(info, scopes=SCOPES)


def _create_in_folder(title: str, folder_id: str) -> str:
    """
    Create a blank Google Sheet directly inside folder_id using the Drive
    v3 REST API with an AuthorizedSession.  The file is owned by the folder
    and counts against the folder owner's quota, NOT the service account's.

    Returns the new spreadsheet file ID.
    """
    info = _decode_sa_json()
    creds = Credentials.from_service_account_info(info, scopes=SCOPES)
    session = AuthorizedSession(creds)
    resp = session.post(
        _DRIVE_FILES_URL,
        params={"fields": "id", "supportsAllDrives": "true"},
        json={
            "name":     title,
            "mimeType": "application/vnd.google-apps.spreadsheet",
            "parents":  [folder_id],
        },
    )
    if not resp.ok:
        raise RuntimeError(
            f"Drive create-in-folder failed (HTTP {resp.status_code}): "
            f"{resp.text[:400]}"
        )
    return resp.json()["id"]


def create_outreach_sheet(title: str, xlsx_path: str) -> dict:
    """
    Read the 'Outreach List' sheet from an openpyxl xlsx file
    (generated by mail_merge/utils/excel_writer.py), write all rows
    to a new Google Sheet, freeze the header row, and share it as
    "anyone with link can edit".

    If GOOGLE_DRIVE_FOLDER_ID is set, the sheet is moved into that folder
    after creation (so it counts against the folder owner's quota).

    Returns: {"sheet_id": str, "sheet_url": str, "title": str}
    """
    # ── Read Excel output ─────────────────────────────────────────────────
    wb = openpyxl.load_workbook(xlsx_path, data_only=True)

    sheet_name = "Outreach List"
    if sheet_name not in wb.sheetnames:
        sheet_name = wb.sheetnames[0]

    ws = wb[sheet_name]
    raw_rows = [[cell.value for cell in row] for row in ws.iter_rows()]

    if not raw_rows:
        raise ValueError("The merge output file is empty.")

    str_rows = [
        [str(v) if v is not None else "" for v in row]
        for row in raw_rows
    ]
    headers   = str_rows[0]
    data_rows = str_rows[1:]

    # ── Create Google Sheet ───────────────────────────────────────────────
    # If a shared folder is configured, create the file directly inside it
    # via the Drive REST API — this uses the folder owner's quota, not the
    # service account's.  Fall back to root creation if no folder is set.
    gc = _client()
    folder_id = os.environ.get("GOOGLE_DRIVE_FOLDER_ID", "").strip()

    if folder_id:
        file_id = _create_in_folder(title, folder_id)
        sh = gc.open_by_key(file_id)
    else:
        sh = gc.create(title)

    gsheet = sh.sheet1
    gsheet.update_title("Outreach List")

    all_rows = [headers] + data_rows
    gsheet.update(all_rows, "A1")

    gsheet.format(
        f"A1:{_col_letter(len(headers))}1",
        {"textFormat": {"bold": True}},
    )
    gsheet.freeze(rows=1)

    # ── Share publicly ────────────────────────────────────────────────────
    sh.share("", perm_type="anyone", role="writer")

    return {
        "sheet_id":  sh.id,
        "sheet_url": sh.url,
        "title":     title,
    }


def extract_sheet_id(url_or_id: str) -> str:
    """
    Accept either a full Google Sheets URL or a bare spreadsheet ID
    and return just the ID component.
    """
    m = re.search(r"/spreadsheets/d/([a-zA-Z0-9\-_]+)", url_or_id)
    return m.group(1) if m else url_or_id.strip()


def read_sheet_status(sheet_id: str) -> dict:
    """
    Open the sheet by ID, count total data rows and how many have
    Send Status == "Sent".

    Returns: {"total": int, "sent": int, "is_complete": bool}
    """
    gc = _client()
    sh = gc.open_by_key(sheet_id)
    gsheet = sh.sheet1
    records = gsheet.get_all_records()

    data_rows = [r for r in records if str(r.get("Recipient Email", "")).strip()]
    total = len(data_rows)
    sent  = sum(
        1 for r in data_rows
        if str(r.get("Send Status", "")).strip() == "Sent"
    )
    return {"total": total, "sent": sent, "is_complete": (total > 0 and sent >= total)}


def read_leads(sheet_id: str) -> list[dict]:
    """
    Open the sheet by ID, find the 'Lead Status' and 'Recipient Email'
    columns by header name (robust against column reordering), and return
    a list of {"email": str, "status": "Lead"|"Unsubscribe"} for every
    row where Lead Status is one of those two values.

    Rows with status "Reply" or blank are ignored.
    """
    gc = _client()
    sh = gc.open_by_key(sheet_id)
    gsheet = sh.sheet1
    records = gsheet.get_all_records()

    results: list[dict] = []
    for record in records:
        status = str(record.get("Lead Status", "")).strip()
        email  = str(record.get("Recipient Email", "")).strip().lower()
        if status in ("Lead", "Unsubscribe") and email and "@" in email:
            results.append({"email": email, "status": status})
    return results


# ── Internal helpers ──────────────────────────────────────────────────────────

def _col_letter(n: int) -> str:
    """Convert a 1-based column index to an Excel-style letter (1→A, 26→Z, 27→AA)."""
    result = ""
    while n:
        n, rem = divmod(n - 1, 26)
        result = chr(65 + rem) + result
    return result or "A"
