"""
Google Sheets integration helper.

Requires:
  - GOOGLE_SHEETS_SA_JSON env var: base64-encoded service account JSON key
    (Sheets API + Drive API must both be enabled on the Cloud project)

Optional:
  - GOOGLE_DRIVE_FOLDER_ID env var: ID of a Drive folder shared with the
    service account email as Editor. Sheets are created directly there so
    they count against the folder owner's quota, not the service account's.

One-time setup:
  1. Google Cloud Console → enable Sheets API + Drive API
  2. IAM & Admin → Service Accounts → Create → download JSON key
  3. Base64-encode: base64 -w0 service-account.json
  4. Add as GOOGLE_SHEETS_SA_JSON env var in Render
  5. Share your Drive folder with the service account EMAIL (e.g.
     sheets-writer@your-project.iam.gserviceaccount.com) as Editor
  6. Add the folder ID as GOOGLE_DRIVE_FOLDER_ID env var in Render
"""
from __future__ import annotations

import base64
import json
import os
import re

import gspread
import openpyxl
from google.oauth2.service_account import Credentials
from google.auth.transport.requests import AuthorizedSession

SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
]

_DRIVE_FILES_URL = "https://www.googleapis.com/drive/v3/files"


def is_configured() -> bool:
    """Return True if the Google Sheets env var is present."""
    return bool(os.environ.get("GOOGLE_SHEETS_SA_JSON", "").strip())


def _decode_sa_json() -> dict:
    """Decode the base64 service account JSON from the env var."""
    raw = os.environ.get("GOOGLE_SHEETS_SA_JSON", "").strip()
    if not raw:
        raise RuntimeError(
            "GOOGLE_SHEETS_SA_JSON env var is not set. "
            "Follow the setup instructions to configure Google Sheets integration."
        )
    try:
        return json.loads(base64.b64decode(raw + "=="))
    except Exception as exc:
        raise RuntimeError(f"Could not decode GOOGLE_SHEETS_SA_JSON: {exc}") from exc


def _client() -> gspread.Client:
    """Return an authenticated gspread Client (gspread v6 native method)."""
    info = _decode_sa_json()
    return gspread.service_account_from_dict(info, scopes=SCOPES)


def _authed_session() -> AuthorizedSession:
    """Return an AuthorizedSession for direct Drive REST calls."""
    info = _decode_sa_json()
    creds = Credentials.from_service_account_info(info, scopes=SCOPES)
    return AuthorizedSession(creds)


def cleanup_service_account_drive(older_than_days: int = 0) -> dict:
    """
    Delete spreadsheets owned by the service account.
    older_than_days=0 deletes ALL sheets; >0 deletes only older ones.
    Returns {"deleted": int, "errors": int}
    """
    session = _authed_session()
    q = "mimeType='application/vnd.google-apps.spreadsheet' and trashed=false"
    if older_than_days > 0:
        from datetime import datetime, timezone, timedelta
        cutoff = (datetime.now(timezone.utc) - timedelta(days=older_than_days)).strftime("%Y-%m-%dT%H:%M:%S")
        q += f" and createdTime < '{cutoff}'"

    # Page through all matching files
    files, page_token = [], None
    while True:
        params: dict = {"q": q, "fields": "nextPageToken,files(id,name)", "pageSize": 100}
        if page_token:
            params["pageToken"] = page_token
        resp = session.get(_DRIVE_FILES_URL, params=params)
        if not resp.ok:
            break
        data = resp.json()
        files.extend(data.get("files", []))
        page_token = data.get("nextPageToken")
        if not page_token:
            break

    deleted = errors = 0
    for f in files:
        r = session.delete(f"{_DRIVE_FILES_URL}/{f['id']}")
        if r.ok or r.status_code == 204:
            deleted += 1
        else:
            errors += 1
    return {"deleted": deleted, "errors": errors}


def _create_spreadsheet(title: str) -> tuple[str, str]:
    """
    Create a blank Google Sheet via the Sheets API (not the Drive API).
    This bypasses Drive storage quota limits that apply to service accounts.

    Returns (spreadsheet_id, spreadsheet_url).
    """
    session = _authed_session()
    resp = session.post(
        "https://sheets.googleapis.com/v4/spreadsheets",
        json={"properties": {"title": title}},
    )
    if not resp.ok:
        raise RuntimeError(
            f"Sheets API create failed (HTTP {resp.status_code}): "
            f"{resp.text[:400]}"
        )
    data = resp.json()
    sid  = data["spreadsheetId"]
    url  = f"https://docs.google.com/spreadsheets/d/{sid}/edit"
    return sid, url


def create_outreach_sheet(title: str, xlsx_path: str) -> dict:
    """
    Read the 'Outreach List' sheet from an openpyxl xlsx file
    (generated by mail_merge/utils/excel_writer.py), write all rows
    to a new Google Sheet, freeze the header row, and share it as
    "anyone with link can edit".

    Uses the Sheets API (not Drive API) to create the file, which bypasses
    the Drive storage quota limitation that affects GCP service accounts.

    Returns: {"sheet_id": str, "sheet_url": str, "title": str}
    """
    # ── Read Excel output ─────────────────────────────────────────────────
    wb = openpyxl.load_workbook(xlsx_path, data_only=True)

    sheet_name = "Outreach List"
    if sheet_name not in wb.sheetnames:
        sheet_name = wb.sheetnames[0]

    ws = wb[sheet_name]
    raw_rows = [[cell.value for cell in row] for row in ws.iter_rows()]

    if not raw_rows:
        raise ValueError("The merge output file is empty.")

    str_rows = [
        [str(v) if v is not None else "" for v in row]
        for row in raw_rows
    ]
    headers   = str_rows[0]
    data_rows = str_rows[1:]

    # ── Create via Sheets API (bypasses Drive storage quota) ─────────────
    file_id, sheet_url = _create_spreadsheet(title)

    gc     = _client()
    sh     = gc.open_by_key(file_id)
    gsheet = sh.sheet1
    gsheet.update_title("Outreach List")

    all_rows = [headers] + data_rows
    gsheet.update(all_rows, "A1")

    gsheet.format(
        f"A1:{_col_letter(len(headers))}1",
        {"textFormat": {"bold": True}},
    )
    gsheet.freeze(rows=1)

    # ── Share publicly ────────────────────────────────────────────────────
    sh.share("", perm_type="anyone", role="writer")

    return {
        "sheet_id":  file_id,
        "sheet_url": sheet_url,
        "title":     title,
    }


def extract_sheet_id(url_or_id: str) -> str:
    """
    Accept either a full Google Sheets URL or a bare spreadsheet ID
    and return just the ID component.
    """
    m = re.search(r"/spreadsheets/d/([a-zA-Z0-9\-_]+)", url_or_id)
    return m.group(1) if m else url_or_id.strip()


def read_sheet_status(sheet_id: str) -> dict:
    """
    Open the sheet by ID, count total data rows and how many have
    Send Status == "Sent".

    Returns: {"total": int, "sent": int, "is_complete": bool}
    """
    gc = _client()
    sh = gc.open_by_key(sheet_id)
    gsheet = sh.sheet1
    records = gsheet.get_all_records()

    data_rows = [r for r in records if str(r.get("Recipient Email", "")).strip()]
    total = len(data_rows)
    sent  = sum(
        1 for r in data_rows
        if str(r.get("Send Status", "")).strip() == "Sent"
    )
    return {"total": total, "sent": sent, "is_complete": (total > 0 and sent >= total)}


def read_leads(sheet_id: str) -> list[dict]:
    """
    Open the sheet by ID, find the 'Lead Status' and 'Recipient Email'
    columns by header name (robust against column reordering), and return
    a list of {"email": str, "status": "Lead"|"Unsubscribe"} for every
    row where Lead Status is one of those two values.

    Rows with status "Reply" or blank are ignored.
    """
    gc = _client()
    sh = gc.open_by_key(sheet_id)
    gsheet = sh.sheet1
    records = gsheet.get_all_records()

    results: list[dict] = []
    for record in records:
        status = str(record.get("Lead Status", "")).strip()
        email  = str(record.get("Recipient Email", "")).strip().lower()
        if status in ("Lead", "Unsubscribe") and email and "@" in email:
            results.append({"email": email, "status": status})
    return results


# ── Internal helpers ──────────────────────────────────────────────────────────

def _col_letter(n: int) -> str:
    """Convert a 1-based column index to an Excel-style letter (1→A, 26→Z, 27→AA)."""
    result = ""
    while n:
        n, rem = divmod(n - 1, 26)
        result = chr(65 + rem) + result
    return result or "A"
